config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  

  get 'hello_world', to: 'hello_world#index'
  resources :requests
  namespace :api do
    namespace :v1 do
      resources :locations do
        resources :recordings
        end
      end
    end

  get 'lift/index'

  resources :posts

  resources :sewas
  resources :events
 
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/edit'

  get 'password_resets/new'

  
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/edit
  '
  get 'password_resets/new'

  get 'blog/artikel3'
  get 'products/home'

  resources :products do 
    resources :sewas
    
  end

  resources :users do
    member do
      get :history
    end
  end

  resources :products do
    member do 
      get :booked
    end
  end

  resources :products do
    member do
      get :show
    end
  end
  
  resources :products do
    resources :reviews
  end
   
  resources :users do
    resources :komentars
  end

  resources :users do
    resources :products
  end
  resources :sessions
  get 'sessions/new'

  resources :products do
    resources :posts
  end

  resources :users do
    resources :sewas
  end

  resources :users do
    resources :transaksis
  end

  resources :products do
    collection do
      get 'booked'
    end
  end

  resources :products do
    member do
      get :booked
      patch :sewa
    end
  end

  
  get 'blog/index'
  get 'blog/artikel1'
  get 'blog/artikel2'

  get 'pages/home'

  get 'pages/blog'

  namespace :api,defaults: {format: :json}, 
    constraints: { subdomain: 'api' }, path: '/'  do
        scope module: :v1,constraints: ApiConstraints.new(version: 1, default: true) do
      end
  end
  

  resources :weight_classes
  resources :length_classes
  get 'blog/index'

  resources :categories
  get 'welcome/index'

  resources :posts
  get 'pages/home'

  get 'pages/blog'

  
  
  

  
 

  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'
  post 'register' => 'users#new'
  get 'createitem' => 'products#new'
  post 'createitem' => 'products#new'
  get 'home' => 'products#index'
  get 'blog' => 'pages#blog'
  get 'lihat' => 'products#lihat'
  post 'lihat' => 'products#lihat'
  get 'coba' => 'products#edit'
  post 'coba' => 'products#validasi'
  get 'transaksi' => 'products#penawaran'
  get 'myproduct' => 'users#index'
  get 'cara' => 'welcome#caramenyewa'
  
  get 'pesan' => 'users#sewa'
  
  
  get 'syaratdanketentuan' => 'welcome#syarat'
  get 'partnerdengankami' => 'welcome#partner'

  get '/products/:product_id/penawarans/:id' => 'penawarans#index'

  get 'products/:id/sewaitem' => 'products#edit',as: :'penawaran'

   resources :users do
    member do
      get :confirm_email
    end
  end

  

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	#@products = Product.reorder("created_at DESC").page(params[:page]).per_page(8)
  	@products = Product.all
  	if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(8)
  	else
    @products = Product.all.order("created_at DESC").page(params[:page]).per_page(8)
  	end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/caramenyewa.html.erb
<%= stylesheet_link_tag "homes" %>
<% provide(:title, 'Sewa Mobil Murah Dan Terbaik') %>

 <div class="header">
      <div class="header-nav">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">        
          
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand"><%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/logonew.png",size:"100x47"),home_path %></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Lihat Mobil",lihat_path %></li>
              <li><%= link_to "Listing Mobil",createitem_path %></li>
              <li><span class="nav-itemButton"><%= link_to "Daftar ",register_path,class:"btn button-smaller" %></li></span>
              <li><%= link_to "Masuk",login_path %></li>
            </ul>
          </div><!-- /navbar-collapse -->
         </div>

        </nav>
  </div>
  </div>
  <br><br>
  <div class="container atas">
    <div class="panel panel-default">
        <div class="panel-heading"><h2><center>Cara Menyewa Mobil di Handbo</center></h2></div>
        <div class="panel-body">
          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/registertutorial.png", class:"img-responsive" %><br>
            <p><b>Langkah Pertama : </b></p>
            <p>Setelah anda mengakses website https://www.handbo.id/ , selanjutnya anda klik pada menu DAFTAR (jika belum mempunyai akun diwebsite).</p>
          </div>
          
          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/menuregister.png", class:"img-responsive" %><br>
            <p><b>Langkah Kedua : </b></p>
            <p>Setelah anda mengklik menu DAFTAR, maka untuk mendaftar akun, selanjutnya isi form tersebut dengan lengkap dan benar.</p><br>
          </div>
         
          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/logintut.png", class:"img-responsive" %><br>
            <p><b>Langkah Ketiga : </b></p>
            <p>Jika sudah mempunyai akun Handbo, langsung MASUK untuk memulai menyewa.</p>
          </div>

          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/homelogin.png", class:"img-responsive" %><br>
            <p><b>Langkah Keempat : </b></p>
            <p>Jika Anda sudah login, makan tampilan website di index menjadi seperti ini, Lalu silahkan melanjutkan untuk memilih mobil yang ingin anda sewa pada menu "Lihat Mobil"</p>
          </div>

          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/homelogin.png", class:"img-responsive" %><br>
            <p><b>Langkah Kelima : </b></p>
            <p>Jika Anda sudah login, makan tampilan website di index menjadi seperti ini, Lalu silahkan melanjutkan untuk memilih mobil yang ingin anda sewa pada menu "Lihat Mobil"</p>
          </div>

          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/lihattut.png", class:"img-responsive" %><br>
            <p><b>Langkah Keenam : </b></p>
            <p>Ini adalah beberapa list mobil yang dapat anda sewakan, silahkan dipilih dan terdapat juga menu pencarian yang berdasarkan kota, setelah mendapatkan mobil yang akan di. Silahkan anda tekan tombol SEWA</p><br>
          </div>

           <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/formsewatut.png", class:"img-responsive" %><br>
            <p><b>Langkah Ketujuh : </b></p>
            <p>Menu sewa, terdapat keterangan tentang mobil yang anda ingin sewa. Baca dengan benar keterangan agar mobil yang ada sewa sesuai dengan keinginan</p>
          </div>

          <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/booktut.png", class:"img-responsive" %><br>
            <p><b>Langkah Kedelapan : </b></p>
            <p>Setelah membaca keterangan mobilnya, silahkan scrol kebawah terdapat tanggal,bulan,tahun.silahkan pilih sesuai keinginan anda dalam menyewa mobil.</p>
          </div>

           <div class="col-md-6">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/confirmtut.png", class:"img-responsive" %><br>
            <p><b>Langkah Kesembilan : </b></p>
            <p>Isi form booking dengan benar dan valid, lalu tekan tombol confirm booking.</p>
          </div>

           <div class="col-md-6">
            <div class="col-md-4">
            <%= image_tag "https://s3.amazonaws.com/handboaws/home/emailtut.jpg", class:"img-responsive" %><br></div>
            <p><b>Langkah Kesepuluh : </b></p>
            <p>Sesudah anda menekan tombol confirm booking, maka anda mendapat email dari sistem berdasarkan mobil yang anda pilih, dan tunggu konfirmasi dari penyewa.</p>
          </div>
       

        </div>

    </div>
  </div>

<footer>
    <div class="container-fluid text-center">
      <div class="row">
        <div class="col-sm-4 col-xs-4">
          <div class="isifooter1">
            <a style="color: #fff; text-decoration: " href="https://blog.handbo.id/" target="_blank">Blog</a>
          </div>
          <div class="isifooter2">
            <a><%= link_to "Jadi Partner Kami", partnerdengankami_path, {style: "color: white"} %></a>
          </div>
          <div class="isifooter3">
            <a><%= link_to "Syarat dan Ketentuan", syaratdanketentuan_path, {style: "color: white"} %></a>
            </div>
        </div>

          <div class="col-sm-4 col-xs-4">
              <div class="isifooter">
                <p>Follow Us</p>
           
           <%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/twitter.png",size:"15x15"),"https://twitter.com/handboindonesia", target:"_blank" %>
           <%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/facebook1.png",size:"15x15"),"https://www.facebook.com/handboindonesia", target:"_blank"%>
           <%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/insta.png",size:"15x15"),"https://www.instagram.com/handbo", target:"_blank" %>
            </div></div>
          <div class="col-sm-4 col-xs-4">
            <div class="isifooter">
              <a><%= link_to "Butuh Mobil Secepatnya ?",new_request_path, {style: "color: white"} %></a><br>
           </div></div>

          
        <div class="clear"></div>
        <hr>
        <div class="copyright"><p>Made with ♥ from Indonesia 2017</p></div>
      </div>
    </div>  

</footer>
  

 <!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 8963674;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<!-- End of LiveChat code -->

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "homes" %>
<% provide(:title, 'Sewa Mobil Murah Dan Terbaik') %>

 <div class="header">
      <div class="header-nav">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">        
          
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand"><%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/logonew.png",size:"100x47"),home_path %></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Lihat Mobil",lihat_path %></li>
              <li><%= link_to "Listing Mobil",createitem_path %></li>
              <li><span class="nav-itemButton"><%= link_to "Daftar ",register_path,class:"btn button-smaller" %></li></span>
              <li><%= link_to "Masuk",login_path %></li>
            </ul>
          </div><!-- /navbar-collapse -->
         </div>

        </nav>
  </div>
  </div>
    <br>
<div class="banner">
      <div  id="top" class="callbacks_container">
        <ul class="rslides" id="slider3">
          <li>
            <div class="banner-info">
             <%= image_tag "https://s3.amazonaws.com/handboaws/home/avanza.jpg", class:"img-responsive" %>
          <div class="banner-inf">
              <h1>Sewa Mobil</h1><br>
              <p>Termurah dan Terbaik</p><br><br>
                <%= form_tag lihat_path, method: :get do %>
                <%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center" %>
                <%= submit_tag "Search", :name => nil,class:"btn btn-primary" %>
              <% end %>
      </div>
            </div>
          </li>

          <li>
            <div class="banner-info1">
              <%= image_tag "https://s3.amazonaws.com/handboaws/home/ertiga.jpg", class:"img-responsive" %>
            <div class="banner-inf">
              <h1>Sewa Mobil</h1><br>
              <p>Termurah dan Terbaik</p><br><br>
                <%= form_tag lihat_path, method: :get do %>
                <%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center" %>
                <%= submit_tag "Search", :name => nil,class:"btn btn-primary" %>
              <% end %>
            </div>
            </div>
          </li>
          
          

          <li>
            <div class="banner-info2">
              <%= image_tag "https://s3.amazonaws.com/handboaws/home/city.jpg", class:"img-responsive" %>
              <div class="banner-inf">
              <h1>Sewa Mobil</h1><br>
              <p>Termurah dan Terbaik</p><br><br>
                <%= form_tag lihat_path, method: :get do %>
                <%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center"%>
                <%= submit_tag "Search", :name => nil,class:"btn btn-primary" %>
              <% end %>
  
              </div>
            </div>
          </li>
        </ul>
      </div>
<br>


<!-- FUNGSI UANG -->
<div class="container">
<div class="container-fluid text-center"><h2 class="fontslider">Berapa banyak yang akan anda hasilkan ?</h2></div><br>

<div id="slider">
    <form oninput="amount1.value=addCommas(rangeInput.value); 
                   amount2.value=rangeInput2.value; 
            ">
      <div class="container text-center"> 
         <div class="col-md-4">
            <div class="slider-uang"> 
              <h2>Harga sewa mobil anda per hari</h2>  
            <input name="one" class="bar barslider" type="range" id="rangeInput" min="300000" max="5000000" step="50000" />
          <output id="amount1" name="amount1" for="rangeInput">300,000</output></div></div>
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h2>1 bulan berapa kali mobil anda di sewa</h2> 
          <input name="two" class="bar" type="range" id="rangeInput2" min="1" max="31" />
       <output id="amount2" name="amount2" for="rangeInput2">1</output>
          </div>
         <span class="highlight"></span></div>
        <div class="container-fluid text-center">
        <div class="col-md-12">
           <h2>Penghasilan anda sebulan:</h2> 
      <div id="total">300,000</div>
        </div></div>
    </form>
</div>
</div>


<br> <br><br>
<!-- FUNGSI UANG -->

<div class="container">   
<div class="container-fluid text-center"></div> 
    <div class="row">        
            <div class="col-xs-12">
            <div class="kotakmedia">
              <div class="kotakmedia-info">
                <h1> Dapatkan uang dengan menyewakan mobil anda</h1>
                <div class="kotakmedia-btn">
                <%= link_to "Sewakan Mobil Anda" ,createitem_path, class:"btn btn-media" %>
                </div>
            </div>

          </div>
          </div>
          </div>
          </div>

    <!-- Container (Services Section) -->
<div class="container-fluid text-center">
  <h2>Kenapa Handbo Lebih Baik ?</h2>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-calendar logo-small"></span>
      <h4>Menu Booking</h4>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-user logo-small"></span>
      <h4>Menu Profile </h4>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-list-alt logo-small"></span>
      <h4>Reservasi</h4>
    </div>
  </div>
</div>

    <!-- Wrapper for slides -->
<br><br>
<footer>
    <div class="container-fluid text-center">
      <div class="row">
        <div class="col-sm-4 col-xs-4">
          <div class="isifooter1">
            <a style="color: #fff; text-decoration: " href="https://blog.handbo.id/" target="_blank">Blog</a>
          </div>
          <div class="isifooter2">
            <a><%= link_to "Jadi Partner Kami", partnerdengankami_path, {style: "color: white"} %></a>
          </div>
          <div class="isifooter3">
            <a><%= link_to "Syarat dan Ketentuan", syaratdanketentuan_path, {style: "color: white"} %></a>
            </div>
        </div>

          <div class="col-sm-4 col-xs-4">
              <div class="isifooter">
                <p>Panduan</p>
                  <a><%= link_to "Cara Sewa Mobil", cara_path, {style: "color: white"} %></a>
                  <br>
            </div></div>
          <div class="col-sm-4 col-xs-4">
            <div class="isifooter">
              <a><%= link_to "Butuh Mobil Secepatnya ?",new_request_path, {style: "color: white"} %></a><br>
           </div></div>

          
        <div class="clear"></div>
        <hr>
        <div class="copyright"><p>Made with ♥ from Indonesia 2017</p></div>
      </div>
    </div>  

</footer>
  

 <!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 8963674;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<!-- End of LiveChat code -->


<%= javascript_include_tag "responsiveslides.min"%>
 <!-- Slider-starts-Here -->
         <script>
            // You can also use "$(window).load(function() {"
            $(function () {
              // Slideshow 4
              $("#slider3").responsiveSlides({
                auto: false,
                pager: true,
                nav: false,
                speed: 1500,
                namespace: "callbacks",
                before: function () {
                  $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                  $('.events').append("<li>after event fired.</li>");
                }
              });
        
            });
          </script>
      <!--//End-slider-script -->

<script>
$(document).ready(function () {
    $('.bar').on('input', function () {

        var val1 = parseInt($("#rangeInput").val (), 10);
        var val2 = parseInt($("#rangeInput2").val(), 10);

        var sum = val1 * val2;
        $('#total').text (addCommas(sum))

    });
});


function addCommas(nStr)
{
  nStr += '';
  x = nStr.split('.');
  x1 = x[0];
  x2 = x.length > 1 ? '.' + x[1] : '';
  var rgx = /(\d+)(\d{3})/;
  while (rgx.test(x1)) {
    x1 = x1.replace(rgx, '$1' + ',' + '$2');
  }
  return x1 + x2;
}
</script>

<script>window.twttr = (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0],
    t = window.twttr || {};
  if (d.getElementById(id)) return t;
  js = d.createElement(s);
  js.id = id;
  js.src = "https://platform.twitter.com/widgets.js";
  fjs.parentNode.insertBefore(js, fjs);

  t._e = [];
  t.ready = function(f) {
    t._e.push(f);
  };

  return t;
}(document, "script", "twitter-wjs"));</script>

  <script>
  $( function() {
    var availableTags = [
    "Balikpapan","Bandar Lampung","Banyuwangi","Banjarmasin","Batam","Bandung","Bekasi","Bengkulu","Bogor","Cirebon","Cilegon","Depok","Jakarta","Jepara","Kupang","Kediri","Makassar","Mataram","Malang","Magelang","Manado","Medan","Padang","Pekanbaru","Pekalongan","Pontianak","Samarinda","Semarang","Serang","Sukabumi","Surabaya","Tangerang","Yogyakarta","Lombok","Bali"];
    $( "#search" ).autocomplete({
      source: availableTags
    });
  } );
  </script>