config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  

  get 'hello_world', to: 'hello_world#index'
  resources :requests
  namespace :api do
    namespace :v1 do
      resources :locations do
        resources :recordings
        end
      end
    end

  get 'lift/index'

  resources :posts

  resources :sewas
  resources :events
 
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/edit'

  get 'password_resets/new'

  
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/edit
  '
  get 'password_resets/new'

  get 'blog/artikel3'
  get 'products/home'

  resources :products do 
    resources :sewas
    
  end

  resources :users do
    member do
      get :history
    end
  end

  resources :products do
    member do 
      get :booked
    end
  end

  resources :products do
    member do
      get :show
    end
  end
  
  resources :products do
    resources :reviews
  end
   
  resources :users do
    resources :komentars
  end

  resources :users do
    resources :products
  end
  resources :sessions
  get 'sessions/new'

  resources :products do
    resources :posts
  end

  resources :users do
    resources :sewas
  end

  resources :users do
    resources :transaksis
  end

  resources :products do
    collection do
      get 'booked'
    end
  end

  resources :products do
    member do
      get :booked
      patch :sewa
    end
  end

  
  get 'blog/index'
  get 'blog/artikel1'
  get 'blog/artikel2'

  get 'pages/home'

  get 'pages/blog'

  namespace :api,defaults: {format: :json}, 
    constraints: { subdomain: 'api' }, path: '/'  do
        scope module: :v1,constraints: ApiConstraints.new(version: 1, default: true) do
      end
  end
  

  resources :weight_classes
  resources :length_classes
  get 'blog/index'

  resources :categories
  get 'welcome/index'

  resources :posts
  get 'pages/home'

  get 'pages/blog'

  
  
  

  
 

  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'
  post 'register' => 'users#new'
  get 'createitem' => 'products#new'
  post 'createitem' => 'products#new'
  get 'home' => 'products#index'
  get 'blog' => 'pages#blog'
  get 'lihat' => 'products#lihat'
  post 'lihat' => 'products#lihat'
  get 'coba' => 'products#edit'
  post 'coba' => 'products#validasi'
  get 'transaksi' => 'products#penawaran'
  get 'myproduct' => 'users#index'
  get 'cara' => 'welcome#caramenyewa'
  
  get 'pesan' => 'users#sewa'
  
  
  get 'syaratdanketentuan' => 'welcome#syarat'
  get 'partnerdengankami' => 'welcome#partner'

  get '/products/:product_id/penawarans/:id' => 'penawarans#index'

  get 'products/:id/sewaitem' => 'products#edit',as: :'penawaran'

   resources :users do
    member do
      get :confirm_email
    end
  end

  

  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def artikel3
  end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/artikel1.html.erb
<% provide(:title, 'Blog') %>


  	<em>Written by Eben Sinaga  on November 10 2016</em>
    <p>We are rental marketplaces of everything.We are couple into building handbo and are still continuing to develop and grow.</p>
    <p>We will use this blog to keep you updated on new features and changes to handbo </p>
    <p>Thanks for being part of Handbo ! without your transasctions,it would be very lonely for us here </p>
    
<%= link_to 'Back', blog_index_path %>

    

app/views/blog/artikel2.html.erb
<% provide(:title, 'Blog') %>


<!--for image -->
<div class="container">
  <div class="fordown">
  <h3 class="forhead">What is different between borrow and lend ?</h2>
  <img src="https://cruisingthroughmylife.files.wordpress.com/2013/02/borrowing.jpg" class="img-thumbnail" alt="Cinque Terre" width="504" height="236">
  <br>
  <em>Written by Eben Sinaga  on November 16 2016</em>
  </div>
</div>

<p>When we saw new something and then we want to buy it. In other places, We don’t have need money to buy it.Don’t be panic when you don’t have money. We will inform you how to get new something. We will give your our solution.</p>
<ul>1. Borrow
	<br>
	That means to take something from someone with permission and with the intention of giving it back. The key of borrow is you borrow from somebody.</ul>
	
	<ul>For example
		<li>Can I borrow your dictionary ?</li>
		<li>went to the library to borrow some books</li>
	</ul>

<ul>2. Lend
	<br>
	Lend is which is give something to somebody for a limited a period of time.
	The key of lend is you lend something to somebody</ul>

	<ul>for example
		<li>I can lend you my dictionary</li>
		<li>if you need to make a call, I can lend you my phone</li>
	</ul>

<p>There is no answer “NO” to get new something. </p>

<%= link_to 'Back', blog_index_path %>

app/views/blog/artikel3.html.erb
<% provide(:title, 'Blog') %>


<!--for image -->
<div class="container">
  <div class="fordown">
  <h3 class="forhead">How to rent apartment in Germany ?</h2>
  <img src="http://www.homeforrent.de/css/css_site/home_for_rent/grafiken_design/logo.png" width="204" height="156">
  <br>
  <em>Written by Eben Sinaga  on December 6 2016</em>
  </div>
</div>

<p>Finding apartments in Germany these days is normally done by searching the internet or through newspaper ads. Even if you speak good German, the terms used to describe house and apartment rentals may throw you for a loop. This is especially true with abbreviations used in newspaper ads. What if you saw an ad in a newspaper offering an "80QM 3Zi BJ 96 DG BAD WC" apartment? It might not be as unfathomable as you think.</p>
<p>Here are some key words, their abbreviations and what they mean</p>

<ul><li>Quadratmeter (QM or M2)</li> - 
	this is accompanied by a number and tells you how big the apartment is in square meters. Zimmer (Zi) accompanied by a number tells you how many rooms the place has.
	</ul>

<ul><li>The term Baujahr (BJ) </li>
	followed by a number means year built. The terms Water Closet (WC), Bath (Bad) and Dusche (Du) tell you about the sanitary facilities. Bath means only a tub, and a WC is a room with a toilet but no bathing facilities. The words Erdgeschoss (EG), Obergeschoss (OG) and Dachgeschoss (DG) tell you how high up in the building you'll be; respectively "ground floor", "upper floor" and "attic floor"
	</ul>
<ul><li>Kaution</li>
	is the "security deposit" that you must lay down over and above your rent. This is usually followed by a number, which tells you what the security deposit is in euros. Gepflegt (Gepfl) means "well cared for" and Ruhig (Ruh) means "quiet". Nebenkosten (NK) means "incidental expenditures" that may not be included in your rent; such as trash collection, stairwell cleaning and water. If you happen to be looking for a fully furnished apartment, keep an eye peeled for the term Möbliert (Möbl), and if you are looking for such comfortable amenities as central heating, a balcony, a garden or a garage look for Zentralheizung (ZH), Balkon (Balk), Garten (Gart) or Garage (Gge).
</ul>

<p>There are specialists in moving and relocation nowadays; people set up to relieve employees of the problems of acclimation and acculturation. They offer a wide range of services and are continually increasing the breadth and depth of their services.

Large and small companies, as well as individuals moving to foreign countries, seek out the services of these specialists. Without specialized help the task of moving and adjusting can be daunting. The most common responsibilities taken on by relocation specialists include finding housing and schools; address registration; residence permit assistance; help with work permits and banking connections, and arranging for utilities and phone service. In addition to these basics, other services offered can involve help in getting driver's licenses, insurance, career counselling for spouses, vocational training, language and cultural training and finding doctors and dentists. There is also an increased focus on "lifestyle enhancement" services.

The moving and relocation industry has evolved and many companies have formed cooperative relationships and partnerships with other firms within Germany, Europe and worldwide. Many of the international relocation companies have increased the number of offices around the world to meet the new demands of an increasing number of expatriate employees.

Relocating without help is an invitation to frustration and lost productivity. Check out the various companies and sign on with one that will fit your needs. It will be well worth the effort.

 </p>

<%= link_to 'Back', blog_index_path %>

app/views/blog/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <section id="hero1" class="hero">
  <div class="inner">
    <div class="copy">
    <h1 class="text-center">The Handbo blog</h1>
    </div>
  </div>
</section>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="first" role="presentation">
                        <%= link_to "Register",register_path,id:"register-tab" %>
                     </li>
                    <li class="first" role="presentation">
                        <%= link_to "Sign In", login_path,id:"sign-in-tab" %>
                    </li>
                         <% if current_user %>
                        Logged in as <%= current_user.email %>.
                        <%= link_to "Log out", logout_path %>
                        <% end %>
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li class="first" role="presentation">
                        <%= link_to "Home",root_path %>
                    </li>
                </ul>
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    <a href="post.html">
                        <h3><%= link_to "The First Blog", blog_artikel1_path,class:"post-title" %></h3>
                    </a>
                    <p class="post-meta">Written by Eben Sinaga on November 10, 2016</p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                      <h3><%= link_to "What is different between borrow and lend ?",blog_artikel2_path,class:"post-title" %></h3>      
                    <p class="post-meta">Written by Eben Sinaga on November 16, 2016</p>
                </div>
                <hr>
                <!-- Pager -->
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Handbo 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>