config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  

  get 'hello_world', to: 'hello_world#index'
  resources :requests
  namespace :api do
    namespace :v1 do
      resources :locations do
        resources :recordings
        end
      end
    end

  get 'lift/index'

  resources :posts

  resources :sewas
  resources :events
 
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/edit'

  get 'password_resets/new'

  
  resources :password_resets, only: [:new, :create, :edit, :update]
  get 'password_resets/edit
  '
  get 'password_resets/new'

  get 'blog/artikel3'
  get 'products/home'

  resources :products do 
    resources :sewas
    
  end

  resources :users do
    member do
      get :history
    end
  end

  resources :products do
    member do 
      get :booked
    end
  end

  resources :products do
    member do
      get :show
    end
  end
  
  resources :products do
    resources :reviews
  end
   
  resources :users do
    resources :komentars
  end

  resources :users do
    resources :products
  end
  resources :sessions
  get 'sessions/new'

  resources :products do
    resources :posts
  end

  resources :users do
    resources :sewas
  end

  resources :users do
    resources :transaksis
  end

  resources :products do
    collection do
      get 'booked'
    end
  end

  resources :products do
    member do
      get :booked
      patch :sewa
    end
  end

  
  get 'blog/index'
  get 'blog/artikel1'
  get 'blog/artikel2'

  get 'pages/home'

  get 'pages/blog'

  namespace :api,defaults: {format: :json}, 
    constraints: { subdomain: 'api' }, path: '/'  do
        scope module: :v1,constraints: ApiConstraints.new(version: 1, default: true) do
      end
  end
  

  resources :weight_classes
  resources :length_classes
  get 'blog/index'

  resources :categories
  get 'welcome/index'

  resources :posts
  get 'pages/home'

  get 'pages/blog'

  
  
  

  
 

  root 'welcome#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'
  post 'register' => 'users#new'
  get 'createitem' => 'products#new'
  post 'createitem' => 'products#new'
  get 'home' => 'products#index'
  get 'blog' => 'pages#blog'
  get 'lihat' => 'products#lihat'
  post 'lihat' => 'products#lihat'
  get 'coba' => 'products#edit'
  post 'coba' => 'products#validasi'
  get 'transaksi' => 'products#penawaran'
  get 'myproduct' => 'users#index'
  get 'cara' => 'welcome#caramenyewa'
  
  get 'pesan' => 'users#sewa'
  
  
  get 'syaratdanketentuan' => 'welcome#syarat'
  get 'partnerdengankami' => 'welcome#partner'

  get '/products/:product_id/penawarans/:id' => 'penawarans#index'

  get 'products/:id/sewaitem' => 'products#edit',as: :'penawaran'

   resources :users do
    member do
      get :confirm_email
    end
  end

  

  

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { large: "600x600>", medium: "300x225>", thumb: "100x100>" }, default_url: "public/images"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  	has_attached_file :image2, styles: { large: "600x600>", medium: "300x225>", thumb: "100x100>" }, default_url: "public/images"
  	validates_attachment_content_type :image2, content_type: /\Aimage\/.*\z/
    #mount_uploader :image, ImageUploader
  	#attr_accessor :nama, :item, :descriptions, :price, :from, :until, :stadt, :subitem, :assets_attributes
  	#has_many :assets
  	#accepts_nested_attributes_for :assets, allow_destroy: true, reject_if: lambda {|attributes| attributes['image'].blank?}
  	#attr_accessor :assets_attributes
  has_many :penawarans
	has_many :order_items
	belongs_to :users
	has_many :sewas	

  	has_many :sewas
	validates :description, :subitem, :stadt, :image, :image2, :item, :klasifikasikategory, :item, :tipe, :platnomor, :lepaskunci,:transmisi, presence: { message: "Tidak Boleh Kosong"}
	validates :harga6jam, :harga12jam, :hargafullday, 
				presence: true, 
				format: { with: /\A\d+(?:\.\d{0,2})?\z/ },
				numericality: { greater_than: 0, less_than: 100000000 }

	
	def self.search(search)
		#tire.search(load.true)  do
		#	query{string params[:query],default_operator:"AND"} if params[:query].present?
		#	filter :range,published_at:{lte: Time.zone.now}
		where("lower(item) LIKE? OR lower(stadt) LIKE?", "%#{search.downcase}%","%#{search.downcase}%")
	end
	
	def sewa
		self.tambahanproduk -=1
		self.save
		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :set_product, only: [:sewaitem, :show, :edit, :update, :destroy,:coba,:myproduct]
  #before_action :find_user_object
  before_action :logged_in_user,only:[:update,:destroy,:show,:index,:new]
  before_action :set_product,only: [:show,:booked,:sewa]
  

  # GET /products
  # GET /products.json
  def index
   @user = current_user
   #@product = Product.all
   @products = @user.products.all
   if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(8)
    else
    @products = Product.all.order("created_at DESC").page(params[:page]).per_page(8)
    end
  end

  def home
   
   #@products = Product.reorder("created_at DESC").page(params[:page]).per_page(8)
   @user = current_user   
    @products = Product.all
    if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(8)
    else
    @products = Product.all.order("created_at DESC").page(params[:page]).per_page(8)
    end
  end
  

  # GET /products/1
  # GET /products/1.json
  def show
    @reviews = Review.all.order("created_at DESC")
  end

  def sewa
    redirect_to home_path,notice: "Anda telah nyewa #{@product.item}"
    

  end  

  def search
    @products = Product.all
  end
  
  def sewaitem
 
  end

  def lihat
    #@products = Product.all.paginate(page:params[:page],per_page:10)
    #@products = Product.all.reorder("created_at DESC").page(params[:page]).per_page(8)
      @products = Product.all
  if params[:search]
    @products = Product.search(params[:search]).order("created_at DESC").page(params[:page]).per_page(8)
  else
    @products = Product.all.order("created_at DESC").page(params[:page]).per_page(8)
  end
  end    


  # GET /products/new
  def new
    @product = Product.new

  end

  def validasi
    @products = Product.all
  end
  
  def penawaran
    
  end

# GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
     @user = current_user
    products = current_user.products
    @users = @user.products
  end

  def booked
     
  end


  # POST /products
  # POST /products.json
  def create
   #@user = current_user
    #@product = Product.new(product_params)
    #@product = @user.products.new(product_params)
    @product = current_user.products.create(product_params)

    #if verify_recaptcha(model: @product) && @product.save 

    respond_to do |format|
      if @product.save

        format.html { redirect_to lihat_path,notice: 'Telah berhasil dibuat.' }
        format.json { render :json, status: :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :json, status: :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
   @product = Product.find(params[:id])
    products = current_user.purchases.find_by(product_id: params[:id]).destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to myproduct_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:item, :from,:image,:image2, :tipe, :klasifikasikategory, :platnomor, :stadt, :subitem, :lepaskunci,:transmisi,:current_user_id,:user_id,:product_id,:harga6jam,:booked,:harga12jam,:hargafullday,:description)
    end  

    def find_user_object
      current_user = User.find_by(params[:user_id])
    end

    def logged_in_user
    unless logged_in?
      flash[:danger] ="Please Log in"
      redirect_to login_url
    end    
  end
end

app/helpers/products_helper.rb
module ProductsHelper

def number_to_currency_br(number)
	number_to_currency(number,:unit =>"Rp",:delimiter =>".",:precision =>0)
end

def checked(area)
  @product.produktambahan.nil? ? false : @product.produktambahan.match(area)
end

end

app/views/products/_lihat.html.erb
<ul class="grid">
  <% @products.each do |product| %>
    <div class="panel1">
      <div class="text-center"><h4><%= link_to product.item,new_product_sewa_path(product) %></h4></div>
        <div class="text-center"><%= link_to (image_tag product.image(:medium)),new_product_sewa_path(product) %></div>
          <ul>
          <br>
            <li>Item:&nbsp;</b><%= product.item %></li>
            <li>Tanggal:&nbsp;&nbsp;</b><%= product.from %></li>
            <li>No HP:&nbsp;&nbsp;</b><%= product.subitem %></li> 
          </ul>
        </div>
     <% end %>
      </div>
    </div>
</ul>  

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title><% provide(:title, 'Sewa Mobil Murah Dan Terbaik') %></title>
<%= stylesheet_link_tag "homes" %>
</head>

<body>

<!-- header -->
  <div class="header">
      <div class="header-nav">
        <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand"><%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/logonew.png",size:"100x47"),home_path %></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Lihat Mobil",lihat_path %></li>
              <li><span class="nav-itemButton"><%= link_to "Listing Mobil",createitem_path,class:"btn button-smaller" %></li></span>
              <% if current_user %>
                
            <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        My Account <span class="caret"></span>
                    </a>
                <ul class="dropdown-menu">
                  <li><%= link_to current_user.email, user_path(current_user) %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                        <li><%= link_to "My Car ",myproduct_path %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Logout", logout_path %>
                        </li>
                    </ul>
                </li>
                <% end %>
            </ul>
          </div><!-- /navbar-collapse -->
          </div>
        </nav>
      </div>
    </div>
<br>

<div class="banner">
            <div  id="top" class="callbacks_container">
        <ul class="rslides" id="slider3">
          <li>
            <div class="banner-info">
             <%= image_tag "https://s3.amazonaws.com/handboaws/home/avanza.jpg", class:"img-responsive" %>
          <div class="banner-inf">
              <h1>Sewa Mobil</h1><br>
              <p>Termurah dan Terbaik</p><br><br>
                <%= form_tag lihat_path, method: :get do %>
                <%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center" %>
                <%= submit_tag "Search", :name => nil,class:"btn btn-primary" %>
              <% end %>
      </div>
            </div>
          </li>

          <li>
            <div class="banner-info1">
              <%= image_tag "https://s3.amazonaws.com/handboaws/home/ertiga.jpg", class:"img-responsive" %>
            <div class="banner-inf">
              <h1>Sewa Mobil</h1><br>
              <p>Termurah dan Terbaik</p><br><br>
                <%= form_tag lihat_path, method: :get do %>
                <%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center" %>
                <%= submit_tag "Search", :name => nil,class:"btn btn-primary" %>
              <% end %>
            </div>
            </div>
          </li>
          
          <li>
            <div class="banner-info2">
              <%= image_tag "https://s3.amazonaws.com/handboaws/home/city.jpg", class:"img-responsive" %>
              <div class="banner-inf">
              <h1>Sewa Mobil</h1><br>
              <p>Termurah dan Terbaik</p><br><br>
                <%= form_tag lihat_path, method: :get do %>
                <%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center"%>
                <%= submit_tag "Search", :name => nil,class:"btn btn-primary" %>
              <% end %>
  
              </div>
            </div>
          </li>
        </ul>
      </div>
<br>
<br>
 <!-- FUNGSI UANG -->
<div class="container">
<div class="container-fluid text-center"><h2 class="fontslider">Berapa banyak yang akan anda hasilkan ?</h2></div><br>

<div id="slider">
    <form oninput="amount1.value=addCommas(rangeInput.value); 
                   amount2.value=rangeInput2.value; 
            ">
      <div class="container text-center"> 
         <div class="col-md-4">
            <div class="slider-uang"> 
              <h2>Harga sewa mobil anda per hari</h2>  
            <input name="one" class="bar barslider" type="range" id="rangeInput" min="300000" max="5000000" step="50000" />
          <output id="amount1" name="amount1" for="rangeInput">300,000</output></div></div>
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h2>1 bulan berapa kali mobil anda di sewa</h2> 
          <input name="two" class="bar" type="range" id="rangeInput2" min="1" max="31" />
       <output id="amount2" name="amount2" for="rangeInput2">1</output>
          </div>
         <span class="highlight"></span></div>
        <div class="container-fluid text-center">
        <div class="col-md-12">
           <h2>Penghasilan anda sebulan:</h2> 
      <div id="total">300,000</div>
        </div></div>
    </form>
</div>
</div>


<br> <br><br>
<!-- FUNGSI UANG -->



<div class="container">   
<div class="container-fluid text-center"></div> 
    <div class="row">        
            <div class="col-xs-12">
            <div class="kotakmedia">
              <div class="kotakmedia-info">
                <h1> Dapatkan uang dengan menyewakan mobil anda</h1>
                <div class="kotakmedia-btn">
                <%= link_to "Sewakan Mobil Anda" ,createitem_path, class:"btn btn-media" %>
                </div>
            </div>

          </div>
          </div>
          </div>
          </div>

<div class="container">   
<div class="container-fluid text-center">
<h2> Top Lokasi</h2></div> 
    <div class="row">        
            <div class="col-xs-6 col-md-4 col-lg-4 px-0">
            <div class="kotakkota">
            <div class="kota-photo"><%= image_tag "https://s3.amazonaws.com/handboaws/home/bandung.jpg", class:"img-responsive" %>
              <div class="kota-info">
                <h1> Bandung</h1>
                </div>
            </div>

          </div>
          </div>

          <div class="col-xs-6 col-md-4 col-lg-4 px-0">
            <div class="kotakkota">
            <div class="kota-photo"><%= image_tag "https://s3.amazonaws.com/handboaws/home/bekasi.jpg", class:"img-responsive" %></div>
            <div class="kota-info">
                <h1> Bekasi</h1>
                </div>
          </div>
          </div>

           <div class="col-xs-6 col-md-4 col-lg-4 px-0">
            <div class="kotakkota">
            <div class="kota-photo"><%= image_tag "https://s3.amazonaws.com/handboaws/home/bogor.jpg", class:"img-responsive" %></div>
            <div class="kota-info">
                <h1> Bogor</h1>
                </div>
          </div>
          </div>

          <div class="col-xs-6 col-md-4 col-lg-4 px-0">
            <div class="kotakkota">
            <div class="kota-photo"><%= image_tag "https://s3.amazonaws.com/handboaws/home/depok.jpg", class:"img-responsive" %>
              <div class="kota-info">
                <h1> Depok</h1>
                </div>
            </div>

          </div>
          </div>

          <div class="col-xs-6 col-md-4 col-lg-4 px-0">
            <div class="kotakkota">
            <div class="kota-photo"><%= image_tag "https://s3.amazonaws.com/handboaws/home/jakarta.jpg", class:"img-responsive" %></div>
            <div class="kota-info">
                <h1> Jakarta</h1>
                </div>
          </div>
          </div>

           <div class="col-xs-6 col-md-4 col-lg-4 px-0">
            <div class="kotakkota">
            <div class="kota-photo"><%= image_tag "https://s3.amazonaws.com/handboaws/home/tangerang.jpg", class:"img-responsive" %></div>
            <div class="kota-info">
                <h1> Tangerang</h1>
                </div>
          </div>
          </div>

    </div>  
    </div> 
    </div>

    <!-- Wrapper for slides -->
<br><br>
<footer>
    <div class="container-fluid text-center">
      <div class="row">
        <div class="col-sm-4 col-xs-4">
          <div class="isifooter1">
            <a style="color: #fff; text-decoration: " href="https://blog.handbo.id/" target="_blank">Blog</a>
          </div>
          <div class="isifooter2">
            <a><%= link_to "Jadi Partner Kami", partnerdengankami_path, {style: "color: white"} %></a>
          </div>
          <div class="isifooter3">
            <a><%= link_to "Syarat dan Ketentuan", syaratdanketentuan_path, {style: "color: white"} %></a>
            </div>
        </div>

          <div class="col-sm-4 col-xs-4">
              <div class="isifooter">
                <p>Follow Us</p>
           
           <%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/twitter.png",size:"15x15"),"https://twitter.com/handboindonesia", target:"_blank" %>
           <%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/facebook1.png",size:"15x15"),"https://www.facebook.com/handboindonesia", target:"_blank"%>
           <%= link_to image_tag("https://s3.amazonaws.com/handboaws/home/insta.png",size:"15x15"),"https://www.instagram.com/handbo", target:"_blank" %>
            </div></div>
          <div class="col-sm-4 col-xs-4">
            <div class="isifooter">
              <a><%= link_to "Butuh Mobil Secepatnya ?",new_request_path, {style: "color: white"} %></a>
           </div></div>

          
        <div class="clear"></div>
        <hr>
        <div class="copyright"><p>Made with ♥ from Indonesia 2017</p></div>
      </div>
    </div>  

</footer>        

    <!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 8963674;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<!-- End of LiveChat code -->
</body>
</html>
<%= javascript_include_tag "responsiveslides.min"%>
<!-- Slider-starts-Here -->
         <script>
            // You can also use "$(window).load(function() {"
            $(function () {
              // Slideshow 4
              $("#slider3").responsiveSlides({
                auto: false,
                pager: true,
                nav: false,
                speed: 1500,
                namespace: "callbacks",
                before: function () {
                  $('.events').append("<li>before event fired.</li>");
                },
                after: function () {
                  $('.events').append("<li>after event fired.</li>");
                }
              });
        
            });
          </script>
      <!--//End-slider-script -->

      <script>
$(document).ready(function () {
    $('.bar').on('input', function () {

        var val1 = parseInt($("#rangeInput").val (), 10);
        var val2 = parseInt($("#rangeInput2").val(), 10);

        var sum = val1 * val2;
        $('#total').text (addCommas(sum))

    });
});


function addCommas(nStr)
{
  nStr += '';
  x = nStr.split('.');
  x1 = x[0];
  x2 = x.length > 1 ? '.' + x[1] : '';
  var rgx = /(\d+)(\d{3})/;
  while (rgx.test(x1)) {
    x1 = x1.replace(rgx, '$1' + ',' + '$2');
  }
  return x1 + x2;
}
</script>

<script>
  $( function() {
    var availableTags = [
"Balikpapan","Bandar Lampung","Banyuwangi","Banjarmasin","Batam","Bandung","Bekasi","Bengkulu","Bogor","Cirebon","Cilegon","Depok","Jakarta","Jepara","Kupang","Kediri","Makassar","Mataram","Malang","Magelang","Manado","Medan","Padang","Pekanbaru","Pekalongan","Pontianak","Samarinda","Semarang","Serang","Sukabumi","Surabaya","Tangerang","Yogyakarta","Lombok","Bali"];
    $( "#search" ).autocomplete({
      source: availableTags
    });
  } );
  </script>

app/views/products/lihat.html.erb
<%= stylesheet_link_tag "products" %>
<%= stylesheet_link_tag "homes" %>

<% provide(:title,'Search') %>
<% if current_user %>
<%= render 'layouts/header' %>
<% else %>
 <div class="header">
      <div class="header-nav">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">        
          
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
              <a class="navbar-brand"><%= link_to image_tag("logonew.png",size:"100x47"),root_path %></a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "Lihat Mobil",lihat_path %></li>
              <li><%= link_to "Listing Mobil",createitem_path %></li>
              <li><span class="nav-itemButton"><%= link_to "Daftar ",register_path,class:"btn button-smaller" %></li></span>
              <li><%= link_to "Masuk",login_path %></li>
            </ul>
          </div><!-- /navbar-collapse -->
         </div>

        </nav>
  </div>
  </div>

<% end %>
<br><br><br>
<div class="text-center"><%= form_tag lihat_path, method: :get do %>
    <h5><%= text_field_tag :search, params[:search],placeholder:"Cari Kota",class:"text-center" %>
     <%= submit_tag "Search", :name => nil,class:"btn btn-primary btn-sm" %></h5>
  <% end %>
 </div>

  <div class="col-md-2"><%= link_to "Lihat semua Produk",lihat_path,class:"btn btn-default" %></div>
  <h2>Pencarian</h2>
  <div id="content-wrapper">
  <section>
        <% if @products.count == 0 %>
        <h3>No Result</h3>
        <% end %>
  </section>    
      <ul class="grid">
        <% @products.each do |product| %>
          <div class="panel1">
            <div class="col-sm-6 col-md-6">
              <div class="tcb-product-photo">
              <h4><%= product.item %></h4>
              <%= link_to (image_tag product.image(:medium)),product %>
              </div>
            </div>
            <div class="col-sm-6 col-md-6 ">
            <br>
            <br>
              <div class="col-md-12"><h4><span class="glyphicon glyphicon-tags"></span>&nbsp;&nbsp;<%= product.tipe %></h4></div>
              <div class="col-md-12"><h4><span class="glyphicon glyphicon-map-marker"></span>&nbsp;&nbsp;<%= product.stadt  %></h4></div>
              <div class="col-md-12"><h4>Harga&nbsp;&nbsp;<b><%= number_to_currency_br(product.hargafullday) %></b></h4></div>
            <br>
            
          <td><%= link_to 'Sewa', product, class:"btn btn-success" %></td> 
            </div>
          </div>
          <% end %>
          
      </ul>
    
        <div class="col-md-12 text-center">
    <div class="pagination">
      <%= will_paginate @products %>
    </div>   
    
  </div>   



  <%= render 'layouts/footer' %>

  <!-- Start of LiveChat (www.livechatinc.com) code -->
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 8963674;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script>
<!-- End of LiveChat code -->

<script>
  $( function() {
    var availableTags = [
      "Balikpapan","Bandar Lampung","Banyuwangi","Banjarmasin","Batam","Bandung","Bekasi","Bengkulu","Bogor","Cirebon","Cilegon","Depok","Jakarta","Jepara","Kupang","Kediri","Makassar","Mataram","Malang","Magelang","Manado","Medan","Padang","Pekanbaru","Pekalongan","Pontianak","Samarinda","Semarang","Serang","Sukabumi","Surabaya","Tangerang","Yogyakarta","Lombok","Bali"];
    $( "#search" ).autocomplete({
      source: availableTags
    });
  } );
  </script>

app/views/products/myproduct.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <% user.products.each do |product| %>
        
        <td><%= product.item %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/products/sewa.html.erb
<p> You are sucess </p>